name: Convert Issues to JSON Data

on:
  issues:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues
    types:
      - opened
      - edited
      - reopened
      - labeled

jobs:
  convert_to_config:
    if: contains( github.event.issue.title, 'New Project Configuration' )
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: install dependencies
        shell: bash -l {0}
        run: | 
          npm install js-yaml
          npm i @actions/core
          npm i @actions/github
      
      - name: Generate token from GitHub App
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.CONFIG_UPDATES_GH_APP_ID }}
          private_key: ${{ secrets.CONFIG_UPDATES_GH_APP_PRIVATE_KEY }}
      
      - name: Use local convertIssue action
        uses: ./.github/actions/convertIssue
        with:
          # This controls where the JSON files are generated
          folder: "configs/"
          # This tells the action which GitHub Issue Form template file to use
          issue-template: "add-new-config.yml"
          # This controls which property we use to key the file name
          hash-property-name: "url_abbreviation"
      
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add configs/
          git commit \
            -m "[${{ env.UrlAbbreviation }}] generate config from #${{ github.event.issue.number }}" \
            -m "- Triggered by creating or updating issue #${{ github.event.issue.number }}" \
            -m "- Auto-generated by the \`convert-issue-to-json\` workflow"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: configs/
          branch: new-config-#${{ github.event.issue.number }}
          title: '[${{ env.UrlAbbreviation }}] generate config from #${{ github.event.issue.number }}'
          body: |
            - Triggered by creating or updating issue #${{ github.event.issue.number }}
            - Auto-generated by the \`convert-issue-to-json\` workflow
